{-# LANGUAGE GADTs #-}

-- |
-- Module      : Evolution.Config
-- Description : Every knob of a GP run, collected in one record.
--
-- A 'Config' is the complete description of \"how to run this search\": the
-- shape of the program we are looking for, the limits that keep the search
-- tractable, and the strategy parameters (population size, crossover rate,
-- ...).
--
-- It is a GADT rather than a plain record because of the _fitnessFunction
-- field: it stores an arbitrary function @Tree -> a@ together with the
-- constraint @Ord a@. The constraint is needed by the sorting machinery in
-- "Evolution.Individual", and a GADT lets us carry it along with the value
-- that requires it (a plain record would need @Ord a@ on the whole type,
-- which is awkward for the caller).
--
-- Configs are built once per benchmark by
-- "Benchmark.BenchmarkToConfig.makeConfig" and then handed to
-- 'Evolution.Run.runAndLog'.
module Evolution.Config where

import qualified Data.Map as M
import Evolution.Core (Depth)
import Evolution.SamplerTable (SamplerTable)
import Grammar (GType, ProgramType, Tree)

-- | Number of tree evaluations spent so far (the search's \"fuel\").
--
-- Every individual ever scored counts, including duplicates and failures -
-- it is the currency the run is budgeted in.
type Evaluations = Int

data Config a where
  MkConfig ::
    Ord a =>
    { -- | The input and output type of the desired program.
      -- Defines what a solution must look like (e.g. @[GList GInt] ->> GInt@)
      -- and what the type-directed sampler is allowed to build.
      _programType :: !ProgramType,
      -- | How to sample from terminals and operations for full
      -- (always-maximal-depth) tree generation.
      _fullTable :: !SamplerTable,
      -- | How to sample from terminals and operations for grow
      -- (may-stop-early) tree generation.
      _growTable :: !SamplerTable,
      -- | The max depth of any tree. Children deeper than this are rejected,
      -- which is the main guard against unbounded bloat.
      _maxTreeDepth :: !Depth,
      -- | The max depth of a subtree that is generated by the mutation
      -- operator. Capped separately so mutation cannot build a huge graft
      -- in one step even when the overall tree still has room.
      _maxMutationTreeDepth :: !Depth,
      -- | The max depth of the trees in the *initial* population. Kept
      -- smaller than _maxTreeDepth so evolution has room to grow.
      _maxInitialDepth :: !Depth,
      -- | The number of trees in the population.
      _popSize :: Int,
      -- | How many individuals we generate for each steady-state step
      -- (i.e. how many parents are sampled per iteration).
      _individualsPerStep :: Int,
      -- | For how long the program should run, measured in evaluations.
      _nEvaluations :: Evaluations,
      -- | How to evaluate each tree - the problem-specific scoring function.
      -- Pure so that fitness is deterministic given the tree.
      _fitnessFunction :: Tree -> a,
      -- | How much probability we keep for each rank position: selection
      -- probability decays as @_parentScalar ** rank@, so rank 0 (the best)
      -- gets weight 1, rank 1 gets @_parentScalar@, and so on. Values close
      -- to 1 make selection nearly uniform; small values concentrate it on
      -- the best individuals.
      _parentScalar :: Double,
      -- | The probability of doing a crossover (see
      -- 'Evolution.Run.doCrossover'; its complement is used for mutation).
      _crossoverRate :: Double
    } ->
    Config a
